added MovieListPage component, improved Search, Filter, Search, improved styles
alex-lis-dev/react-mentoring-lis pull request #7
Opened 2024-10-21 23:12 UTC by alex-lis-dev

2024-10-30 13:01 UTC, hicugi requested changes
Major issue - abortion of the search request is not working

2024-10-30 13:01 UTC, hicugi commented on src/components/MovieDetails/MovieDetails.jsx
> +const MovieDetails = ({ movie = null, handleSearchIconClick = () => {} }) => {
You can't have `movie = null` and render a property from it.
Example: `movie.title`, `movie.poster_path` etc.

Rename the `handleSearchIconClick` to `onSearchClick` and don't assign default function into it.

2024-10-30 13:01 UTC, hicugi commented on src/components/MovieForm/MovieForm.jsx
> +    //const formData = new FormData(event.target);
Remove unnecessary comments

2024-10-30 13:01 UTC, hicugi commented on src/components/MovieForm/components/AddAndEditMovieDialog/AddAndEditMovieDialog.jsx
> +    console.log(movieData);
remove

2024-10-30 13:01 UTC, hicugi commented on src/components/MovieForm/components/AddAndEditMovieDialog/AddAndEditMovieDialog.jsx
> +      <Dialog title={AddMovieText} onClose={onClose}>
You can pass the `isOpen` to `Dialog` component with prop like `active`

2024-10-30 13:01 UTC, hicugi commented on src/components/MovieForm/components/DeleteMovieDialog/DeleteMovieDialog.jsx
> +    isOpen && (
So you don't have to repeat the same behaviour here

2024-10-30 13:01 UTC, hicugi commented on src/components/MovieListPage/MovieListPage.jsx
> +    // ...new Set(
remove

2024-10-30 13:01 UTC, hicugi commented on src/components/MovieListPage/MovieListPage.jsx
> +  const [selectedMovie, setSelectedMovie] = useState();
The `selectedMovie` should be `null` by default

2024-10-31 09:08 UTC, alex-lis-dev commented on src/components/MovieDetails/MovieDetails.jsx
> +const MovieDetails = ({ movie = null, handleSearchIconClick = () => {} }) => {
removed default values, corrected naming

2024-10-31 09:08 UTC, alex-lis-dev commented on src/components/MovieForm/components/AddAndEditMovieDialog/AddAndEditMovieDialog.jsx
> +    console.log(movieData);
removed

2024-10-31 09:09 UTC, alex-lis-dev commented on src/components/MovieForm/MovieForm.jsx
> +    //const formData = new FormData(event.target);
removed

2024-10-31 09:09 UTC, alex-lis-dev commented on src/components/MovieForm/components/AddAndEditMovieDialog/AddAndEditMovieDialog.jsx
> +      <Dialog title={AddMovieText} onClose={onClose}>
corrected

2024-10-31 09:09 UTC, alex-lis-dev commented on src/components/MovieForm/components/DeleteMovieDialog/DeleteMovieDialog.jsx
> +    isOpen && (
corrected

2024-10-31 09:09 UTC, alex-lis-dev commented on src/components/MovieListPage/MovieListPage.jsx
> +  const [selectedMovie, setSelectedMovie] = useState();
done

2024-10-31 09:10 UTC, alex-lis-dev commented on src/components/MovieListPage/MovieListPage.jsx
> +    // ...new Set(
removed

2024-10-31 09:11 UTC, alex-lis-dev commented
The corrections are applied, console logs and comments are removed

2024-10-31 09:16 UTC, merged